clear;
clc;
close all;

% =========================================================
% LOAD STACKED DATA
% =========================================================

LPMMA = load( ...
'Y:\Masud\Twinkling_signal_process\Twinkle_paper_Data\L7-4\PW\LPMMA\AverageResults2\LTwinkling_AllSamples_Stacked.mat');

PMMA = load( ...
'Y:\Masud\Twinkling_signal_process\Twinkle_paper_Data\L7-4\PW\PMMA\AverageResults2\Twinkling_AllSamples_Stacked.mat');

Metal = load( ...
'Y:\Masud\Twinkling_signal_process\Twinkle_paper_Data\L7-4\PW\Metal_Retake\AverageResults2\Metal_Retake_AllSamples_Stacked.mat');

% =========================================================
% DATA: y(25) x(31) x frame(20) x rep(6) x sample(5)
% =========================================================

PMMA_PD  = PMMA.PD_all;
LPMMA_PD = LPMMA.PD_all;
Metal_PD = Metal.PD_all;

% =========================================================
% MEAN OVER y(1), x(2), rep(4) → frame(20) x sample(5)
% =========================================================

PMMA_sampleMean  = squeeze(mean(mean(mean(PMMA_PD,  1), 2), 4));
LPMMA_sampleMean = squeeze(mean(mean(mean(LPMMA_PD, 1), 2), 4));
Metal_sampleMean = squeeze(mean(mean(mean(Metal_PD,  1), 2), 4));

% =========================================================
% GROUP MEAN ACROSS SAMPLES → frame x 1  (for subplot a)
% =========================================================

PMMA_mean  = mean(PMMA_sampleMean,  2);
LPMMA_mean = mean(LPMMA_sampleMean, 2);
Metal_mean = mean(Metal_sampleMean, 2);

% =========================================================
% MEDIAN OVER FRAMES → 5x1 scalar per sample (for subplot b)
% =========================================================

PMMA_med  = median(PMMA_sampleMean,  1)';
LPMMA_med = median(LPMMA_sampleMean, 1)';
Metal_med = median(Metal_sampleMean, 1)';

frames = (1:20)';

% =========================================================
% OUTPUT FOLDER
% =========================================================

outDir = 'Y:\Masud\Twinkling_signal_process\Twinkle_paper_Data\L7-4\PW\PD_comparison_paper\IUS';
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

% =========================================================
% COLORS (colorblind-safe)
% =========================================================

cPMMA  = [0.16, 0.47, 0.84];
cLPMMA = [0.07, 0.69, 0.48];
cMetal = [0.89, 0.29, 0.28];

alphaIndiv = 0.20;

% =========================================================
% FIGURE — 6.5 x 3.2 inches to fit Word (1" margins)
% =========================================================

% fig = figure('Color',    'w',           ...
%              'Units',    'inches',      ...
%              'Position', [1.4 1.4 8 4], ...
%              'PaperUnits',    'inches', ...
%              'PaperSize',     [6.5 3.2], ...
%              'PaperPosition', [0 0 6.5 3.2]);
% 
% % ── consistent font for all axes ─────────────────────────
% fontName = 'Arial';
% fontSize = 11;           % 7 pt body text is standard in journals
% titleSize = 14;

fig = figure('Color','w', ...
    'Units','inches', ...
    'Position',[1.4 1.4 10 5.5], ...
    'PaperUnits','inches', ...
    'PaperSize',[10 5.5], ...
    'PaperPosition',[0 0 10 5.5]);

fontName  = 'Arial';
fontSize  = 18;
titleSize = 18;
legendSize = 18;

% =========================================================
% SUBPLOT (a) — Frame-wise trajectories
% =========================================================

ax1 = subplot(1, 2, 1);
hold(ax1, 'on');

% individual sample lines
for s = 1:5
    semilogy(ax1, frames, PMMA_sampleMean(:,s),  '-', 'Color', [cPMMA  alphaIndiv], 'LineWidth', 0.8);
    semilogy(ax1, frames, LPMMA_sampleMean(:,s), '-', 'Color', [cLPMMA alphaIndiv], 'LineWidth', 0.8);
    semilogy(ax1, frames, Metal_sampleMean(:,s), '-', 'Color', [cMetal alphaIndiv], 'LineWidth', 0.8);
end

% bold group mean lines
hP = semilogy(ax1, frames, PMMA_mean,  '-', 'Color', cPMMA,  'LineWidth', 2);
hL = semilogy(ax1, frames, LPMMA_mean, '-', 'Color', cLPMMA, 'LineWidth', 2);
hM = semilogy(ax1, frames, Metal_mean, '-', 'Color', cMetal,  'LineWidth', 2);

set(ax1, ...
    'YScale',         'log',            ...
    'XLim',           [1 20],           ...
    'XTick',          [1 5 10 15 20],   ...
            'YLim', [1e1 1e10], ...
    'YTick', [1e5 1e6 1e7 1e8 1e9 1e10], ...
    'TickDir',        'out',            ...
    'TickLength',     [0.015 0.015],    ...
    'Box',            'off',            ...
    'FontName',       fontName,         ...
    'FontSize',       fontSize,         ...
         'FontWeight',     'bold',         ...
    'LineWidth',      0.6,              ...
    'XColor',         [0 0 0],          ...
    'YColor',         [0 0 0]);

grid(ax1, 'on');
ax1.GridAlpha       = 0.15;
ax1.GridColor       = [0.5 0.5 0.5];
ax1.MinorGridAlpha  = 0.08;
ax1.YMinorGrid      = 'on';

xlabel(ax1, 'Frame number',                        'FontSize', fontSize,'FontWeight', 'bold', 'FontName', fontName);
ylabel(ax1, 'Mean power Doppler signal (a.u.)',    'FontSize', fontSize,'FontWeight', 'bold', 'FontName', fontName);
% title(ax1,  '(a)',                                 'FontSize', titleSize, 'FontName', fontName, ...
%             'FontWeight', 'bold', 'HorizontalAlignment', 'left');
text(ax1, -0.18, 1.06, '(a)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom');

legend(ax1, [hP, hL, hM], ...
    {'PMMA', 'LPMMA', 'Metal'},  ...
    'Location',  'best',         ...
    'FontSize',  16,              ...
    'FontName',  fontName,       ...
    'Box',       'on',           ...
    'EdgeColor', [0.7 0.7 0.7], ...
    'LineWidth', 0.5);
% leg = legend(ax1, [hP, hL, hM], ...
%     {'PMMA', 'LPMMA', 'Metal'}, ...
%     'Location',   'best',      ...
%     'FontSize',   8,                ...
%     'FontName',   fontName,         ...
%     'Box',        'on',             ...
%     'EdgeColor',  [0.7 0.7 0.7],   ...
%     'LineWidth',  0.5);

% footnote inside axes
% text(ax1, 0.99, 0.02, ...
%     {'Thin lines: individual samples (n\,=\,5)', 'Bold lines: group mean'}, ...
%     'Units',               'normalized',   ...
%     'HorizontalAlignment', 'right',        ...
%     'VerticalAlignment',   'bottom',       ...
%     'FontSize',            5.5,            ...
%     'FontName',            fontName,       ...
%     'Color',               [0.45 0.45 0.45]);

% =========================================================
% SUBPLOT (b) — Box plot of per-sample median PD
% =========================================================

ax2 = subplot(1, 2, 2);
hold(ax2, 'on');

% --- build 5x3 matrix: columns = PMMA, LT-PMMA, Metal ---
boxData = [PMMA_med, LPMMA_med, Metal_med];

bp = boxplot(ax2, boxData, ...
    'Labels',      {'PMMA', 'LPMMA', 'Metal'}, ...
    'Colors',      [cPMMA; cLPMMA; cMetal],       ...
    'Symbol',      '',      ...   % hide default outlier markers
    'Widths',      0.40,    ...
    'MedianStyle', 'line',  ...
    'Notch',       'off');

set(bp, 'LineWidth', 1.5);

% color box faces
hBox = findobj(ax2, 'Tag', 'Box');
% boxplot draws boxes in reverse order
patch(get(hBox(3), 'XData'), get(hBox(3), 'YData'), cPMMA,  'FaceAlpha', 0.20, 'EdgeColor', cPMMA,  'LineWidth', 1.2);
patch(get(hBox(2), 'XData'), get(hBox(2), 'YData'), cLPMMA, 'FaceAlpha', 0.20, 'EdgeColor', cLPMMA, 'LineWidth', 1.2);
patch(get(hBox(1), 'XData'), get(hBox(1), 'YData'), cMetal, 'FaceAlpha', 0.20, 'EdgeColor', cMetal, 'LineWidth', 1.2);

% jittered individual dots
rng(42);
jitter = (rand(5,1) - 0.5) * 0.12;

scatter(ax2, 1 + jitter, PMMA_med,  18, cPMMA,  'filled', 'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');
scatter(ax2, 2 + jitter, LPMMA_med, 18, cLPMMA, 'filled', 'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');
scatter(ax2, 3 + jitter, Metal_med, 18, cMetal,  'filled', 'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');

set(ax2, ...
    'YScale',         'log',          ...
    'XLim',           [0.4 3.6],      ...
        'YLim', [1e1 1e10], ...
    'YTick', [ 1e5 1e6 1e7 1e8 1e9 1e10], ...
    'TickDir',        'out',          ...
    'TickLength',     [0.015 0.015],  ...
    'Box',            'off',          ...
    'FontName',       fontName,       ...
    'FontSize',       fontSize,       ...
     'FontWeight',     'bold',         ...
    'LineWidth',      0.6,            ...
    'XColor',         [0 0 0],        ...
    'YColor',         [0 0 0]);

grid(ax2, 'on');
ax2.GridAlpha      = 0.15;
ax2.GridColor      = [0.5 0.5 0.5];
ax2.YMinorGrid     = 'on';
ax2.MinorGridAlpha = 0.08;

ylabel(ax2, 'Median power Doppler signal (a.u.)', 'FontSize', fontSize,'FontWeight', 'bold', 'FontName', fontName);
% title(ax2,  '(b)',                                 'FontSize', titleSize,'FontWeight', 'bold', 'FontName', fontName, ...
%             'FontWeight', 'bold', 'HorizontalAlignment', 'left');

text(ax2, -0.18, 1.06, '(b)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom');

legend(ax1, [hP, hL, hM], ...
    {'PMMA', 'LPMMA', 'Metal'}, ...
    'Location','best', ...
    'FontSize',16, ...
    'FontName','Arial', ...
    'Box','on', ...
    'EdgeColor',[0.7 0.7 0.7], ...
    'LineWidth',0.5);
% text(ax2, 0.99, 0.02, 'Dots: individual samples (n\,=\,5)', ...
%     'Units',               'normalized',   ...
%     'HorizontalAlignment', 'right',        ...
%     'VerticalAlignment',   'bottom',       ...
%     'FontSize',            5.5,            ...
%     'FontName',            fontName,       ...
%     'Color',               [0.45 0.45 0.45]);

% =========================================================
% TIGHT LAYOUT
% =========================================================

% set(ax1, 'Position', [0.09  0.17  0.40  0.72]);
% set(ax2, 'Position', [0.60  0.17  0.36  0.72]);
set(ax1, 'Position', [0.14 0.16 0.38 0.74]);
set(ax2, 'Position', [0.64 0.16 0.34 0.74]);
% =========================================================
% SAVE — PNG, PDF, and .fig
% =========================================================

exportgraphics(fig, fullfile(outDir, 'PD_combined_figure.png'), ...
    'Resolution', 600, 'BackgroundColor', 'white');

exportgraphics(fig, fullfile(outDir, 'PD_combined_figure.pdf'), ...
    'ContentType', 'vector', 'BackgroundColor', 'white');

savefig(fig, fullfile(outDir, 'PD_combined_figure.fig'));

fprintf('Saved to: %s\n', outDir);


%% Beamformed RF (With WF)


% =========================================================
% DATA:
% fSIG_rf_all → y × x × pulse × frame × repetition × sample
%                1    2    3       4         5           6
% =========================================================

PMMA_RF  = abs(PMMA.fSIG_rf_all);
LPMMA_RF = abs(LPMMA.fSIG_rf_all);
Metal_RF = abs(Metal.fSIG_rf_all);

% =========================================================
% MEAN OVER y(1), x(2), pulse(3), rep(5)
% → frame(4) × sample(6)
% → Final: 20 × 5
% =========================================================

PMMA_sampleMean  = squeeze(mean(mean(mean(mean(PMMA_RF,  1), 2), 3), 5));
LPMMA_sampleMean = squeeze(mean(mean(mean(mean(LPMMA_RF, 1), 2), 3), 5));
Metal_sampleMean = squeeze(mean(mean(mean(mean(Metal_RF,  1), 2), 3), 5));

% =========================================================
% GROUP MEAN ACROSS SAMPLES → frame × 1  (subplot a)
% =========================================================

PMMA_mean  = mean(PMMA_sampleMean,  2);
LPMMA_mean = mean(LPMMA_sampleMean, 2);
Metal_mean = mean(Metal_sampleMean, 2);

% =========================================================
% MEDIAN OVER FRAMES → 5×1 per sample  (subplot b)
% =========================================================

PMMA_med  = median(PMMA_sampleMean,  1)';
LPMMA_med = median(LPMMA_sampleMean, 1)';
Metal_med = median(Metal_sampleMean, 1)';

frames = (1:20)';

% =========================================================
% OUTPUT FOLDER
% =========================================================

outDir = 'Y:\Masud\Twinkling_signal_process\Twinkle_paper_Data\L7-4\PW\BF_RF_paper\IUS';
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

% =========================================================
% COLORS (colorblind-safe, consistent with PD figure)
% =========================================================

cPMMA  = [0.16, 0.47, 0.84];
cLPMMA = [0.07, 0.69, 0.48];
cMetal = [0.89, 0.29, 0.28];

alphaIndiv = 0.20;

% =========================================================
% FIGURE — 6.5 × 3.2 inches (fits Word page, 1" margins)
% =========================================================

% fig = figure('Color',          'w',          ...
%              'Units',          'inches',     ...
%              'Position',       [1.4 1.4 8 4], ...
%              'PaperUnits',     'inches',     ...
%              'PaperSize',      [6.5 3.2],    ...
%              'PaperPosition',  [0 0 6.5 3.2]);
% 
% fontName  = 'Arial';
% fontSize  = 11;
% titleSize = 14;
fig = figure('Color','w', ...
    'Units','inches', ...
    'Position',[1.4 1.4 10 5.5], ...
    'PaperUnits','inches', ...
    'PaperSize',[10 5.5], ...
    'PaperPosition',[0 0 10 5.5]);

fontName  = 'Arial';
fontSize  = 18;
titleSize = 18;
legendSize = 18;


% =========================================================
% SUBPLOT (a) — Frame-wise trajectories
% =========================================================

ax1 = subplot(1, 2, 1);
hold(ax1, 'on');

% --- individual sample lines (thin, translucent) ---------
for s = 1:5
    semilogy(ax1, frames, PMMA_sampleMean(:,s),  '-', ...
        'Color', [cPMMA  alphaIndiv], 'LineWidth', 0.8);
    semilogy(ax1, frames, LPMMA_sampleMean(:,s), '-', ...
        'Color', [cLPMMA alphaIndiv], 'LineWidth', 0.8);
    semilogy(ax1, frames, Metal_sampleMean(:,s), '-', ...
        'Color', [cMetal alphaIndiv], 'LineWidth', 0.8);
end

% --- bold group mean lines --------------------------------
hP = semilogy(ax1, frames, PMMA_mean,  '-', 'Color', cPMMA,  'LineWidth', 2);
hL = semilogy(ax1, frames, LPMMA_mean, '-', 'Color', cLPMMA, 'LineWidth', 2);
hM = semilogy(ax1, frames, Metal_mean, '-', 'Color', cMetal,  'LineWidth', 2);

set(ax1, ...
    'YScale',     'log',          ...
    'XLim',       [1 20],         ...
    'XTick',      [1 5 10 15 20], ...
     'YLim', [1e1 1e4], ...
    'YTick', [1e1 1e2 1e3 1e4], ...
    'TickDir',    'out',          ...
    'TickLength', [0.015 0.015],  ...
    'Box',        'off',          ...
    'FontName',   fontName,       ...
    'FontSize',   fontSize,       ...
    'FontWeight', 'bold',         ...
    'LineWidth',  0.6,            ...
    'XColor',     [0 0 0],        ...
    'YColor',     [0 0 0]);

grid(ax1, 'on');
ax1.GridAlpha      = 0.15;
ax1.GridColor      = [0.5 0.5 0.5];
ax1.MinorGridAlpha = 0.08;
ax1.YMinorGrid     = 'on';

xlabel(ax1, 'Frame number',                      ...
    'FontSize', fontSize, 'FontWeight', 'bold', 'FontName', fontName);
ylabel(ax1, 'Mean BF RF signal magnitude (a.u.)', ...
    'FontSize', fontSize, 'FontWeight', 'bold', 'FontName', fontName);

text(ax1, -0.18, 1.06, '(a)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom');
% title(ax1, '(a)',                                 ...
%     'FontSize', titleSize, 'FontWeight', 'bold',  ...
%     'FontName', fontName, 'HorizontalAlignment', 'left');

legend(ax1, [hP, hL, hM], ...
    {'PMMA', 'LPMMA', 'Metal'},  ...
    'Location',  'best',         ...
    'FontSize',  16,              ...
    'FontName',  fontName,       ...
    'Box',       'on',           ...
    'EdgeColor', [0.7 0.7 0.7], ...
    'LineWidth', 0.5);

% =========================================================
% SUBPLOT (b) — Box plot of per-sample median RF
% =========================================================

ax2 = subplot(1, 2, 2);
hold(ax2, 'on');

boxData = [PMMA_med, LPMMA_med, Metal_med];   % 5 × 3

bp = boxplot(ax2, boxData,                     ...
    'Labels',      {'PMMA', 'LPMMA', 'Metal'}, ...
    'Colors',      [cPMMA; cLPMMA; cMetal],    ...
    'Symbol',      '',                         ...
    'Widths',      0.40,                       ...
    'MedianStyle', 'line',                     ...
    'Notch',       'off');

set(bp, 'LineWidth', 1.5);

% --- color box faces (boxplot reverses order) -------------
hBox = findobj(ax2, 'Tag', 'Box');
patch(get(hBox(3),'XData'), get(hBox(3),'YData'), cPMMA,  ...
    'FaceAlpha', 0.20, 'EdgeColor', cPMMA,  'LineWidth', 1.2);
patch(get(hBox(2),'XData'), get(hBox(2),'YData'), cLPMMA, ...
    'FaceAlpha', 0.20, 'EdgeColor', cLPMMA, 'LineWidth', 1.2);
patch(get(hBox(1),'XData'), get(hBox(1),'YData'), cMetal, ...
    'FaceAlpha', 0.20, 'EdgeColor', cMetal, 'LineWidth', 1.2);

% --- jittered individual sample dots ----------------------
rng(42);
jitter = (rand(5,1) - 0.5) * 0.12;

scatter(ax2, 1 + jitter, PMMA_med,  18, cPMMA,  'filled', ...
    'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');
scatter(ax2, 2 + jitter, LPMMA_med, 18, cLPMMA, 'filled', ...
    'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');
scatter(ax2, 3 + jitter, Metal_med, 18, cMetal,  'filled', ...
    'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');

set(ax2, ...
    'YScale',     'log',         ...
    'XLim',       [0.4 3.6],     ...
        'YLim', [1e1 1e4], ...
    'YTick', [1e1 1e2 1e3 1e4], ...
    'TickDir',    'out',         ...
    'TickLength', [0.015 0.015], ...
    'Box',        'off',         ...
    'FontName',   fontName,      ...
    'FontSize',   fontSize,      ...
    'FontWeight', 'bold',        ...
    'LineWidth',  0.6,           ...
    'XColor',     [0 0 0],       ...
    'YColor',     [0 0 0]);

grid(ax2, 'on');
ax2.GridAlpha      = 0.15;
ax2.GridColor      = [0.5 0.5 0.5];
ax2.YMinorGrid     = 'on';
ax2.MinorGridAlpha = 0.08;

ylabel(ax2, 'Median BF RF signal magnitude (a.u.)', ...
    'FontSize', fontSize, 'FontWeight', 'bold', 'FontName', fontName);
% title(ax2, '(b)',                                    ...
%     'FontSize', titleSize, 'FontWeight', 'bold',     ...
%     'FontName', fontName,  'HorizontalAlignment', 'left');

text(ax2, -0.18, 1.06, '(b)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom');
legend(ax1, [hP, hL, hM], ...
    {'PMMA', 'LPMMA', 'Metal'},  ...
    'Location',  'best',         ...
    'FontSize',  16,              ...
    'FontName',  fontName,       ...
    'Box',       'on',           ...
    'EdgeColor', [0.7 0.7 0.7], ...
    'LineWidth', 0.5);
% =========================================================
% TIGHT LAYOUT
% =========================================================

% set(ax1, 'Position', [0.09  0.17  0.40  0.72]);
% set(ax2, 'Position', [0.60  0.17  0.36  0.72]);
set(ax1, 'Position', [0.12 0.16 0.38 0.74]);
set(ax2, 'Position', [0.62 0.16 0.34 0.74]);
% =========================================================
% SAVE — PNG, PDF, .fig
% =========================================================

exportgraphics(fig, fullfile(outDir, 'BF_RF_combined_figure.png'), ...
    'Resolution', 600, 'BackgroundColor', 'white');

exportgraphics(fig, fullfile(outDir, 'BF_RF_combined_figure.pdf'), ...
    'ContentType', 'vector', 'BackgroundColor', 'white');

savefig(fig, fullfile(outDir, 'BF_RF_combined_figure.fig'));

fprintf('Saved to: %s\n', outDir);

%% Beamformed IQ (With WF)

% =========================================================
% DATA:
% fSIG_all → y × x × pulse × frame × repetition × sample
%             1    2    3       4         5           6
% =========================================================

PMMA_SIG  = PMMA.fSIG_all;
LPMMA_SIG = LPMMA.fSIG_all;
Metal_SIG = Metal.fSIG_all;

% =========================================================
% FUNCTION HANDLE
% Mean over y(1), x(2), pulse(3), rep(5) → frame(4) × sample(6)
% =========================================================

calcMean = @(X) squeeze(mean(mean(mean(mean(X,1),2),3),5));

% =========================================================
% DECOMPOSE
% =========================================================

% --- Real ------------------------------------------------
PMMA_real_sm  = calcMean(real(PMMA_SIG));
LPMMA_real_sm = calcMean(real(LPMMA_SIG));
Metal_real_sm = calcMean(real(Metal_SIG));

% --- Imaginary -------------------------------------------
PMMA_imag_sm  = calcMean(imag(PMMA_SIG));
LPMMA_imag_sm = calcMean(imag(LPMMA_SIG));
Metal_imag_sm = calcMean(imag(Metal_SIG));

% --- Magnitude -------------------------------------------
PMMA_mag_sm   = calcMean(abs(PMMA_SIG));
LPMMA_mag_sm  = calcMean(abs(LPMMA_SIG));
Metal_mag_sm  = calcMean(abs(Metal_SIG));

% =========================================================
% OUTPUT FOLDER
% =========================================================

outDir = 'Y:\Masud\Twinkling_signal_process\Twinkle_paper_Data\L7-4\PW\IQ_paper\IUS';
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

% =========================================================
% SHARED SETTINGS
% =========================================================

cPMMA     = [0.16, 0.47, 0.84];
cLPMMA    = [0.07, 0.69, 0.48];
cMetal    = [0.89, 0.29, 0.28];
alphaIndiv = 0.20;

% fig = figure('Color','w', ...
%     'Units','inches', ...
%     'Position',[1.4 1.4 18 8], ...
%     'PaperUnits','inches', ...
%     'PaperSize',[14 7], ...
%     'PaperPosition',[0 0 16 7]);

fontName  = 'Arial';
fontSize  = 18;
titleSize = 18;
legendSize = 18;

frames    = (1:20)';

rng(42);
jitter = (rand(5,1) - 0.5) * 0.12;

% =========================================================
% HELPER: build one publication figure
%
% Inputs:
%   sm_P, sm_L, sm_M  — frame×sample matrices (20×5)
%   yLabel             — y-axis label string
%   figTitle           — sgtitle string
%   useLog             — true for magnitude, false for real/imag
%   fname              — base filename (no extension)
% =========================================================

components = { ...
    PMMA_real_sm,  LPMMA_real_sm,  Metal_real_sm,  ...
        'Mean real IQ signal (a.u.)',      ...
        'IQ Real component',               false, 'IQ_Real';  ...
    PMMA_imag_sm,  LPMMA_imag_sm,  Metal_imag_sm,  ...
        'Mean imaginary IQ signal (a.u.)', ...
        'IQ Imaginary component',          false, 'IQ_Imag';  ...
    PMMA_mag_sm,   LPMMA_mag_sm,   Metal_mag_sm,   ...
        'Mean |IQ| signal (a.u.)',         ...
        'IQ Magnitude',                    true,  'IQ_Magnitude'};

% components rows: smP, smL, smM, yLab, figTit, useLog, fname
% Each row has 7 entries — loop over 3 figures

nFig = 3;
colIdx = [1 2 3 4 5 6 7];   % column indices per row

for f = 1:nFig

    row   = f;
    sm_P  = components{row, 1};
    sm_L  = components{row, 2};
    sm_M  = components{row, 3};
    yLab  = components{row, 4};
    fTit  = components{row, 5};
    useLog= components{row, 6};
    fname = components{row, 7};

    % --- group means (frame×1) ---------------------------
    mu_P = mean(sm_P, 2);
    mu_L = mean(sm_L, 2);
    mu_M = mean(sm_M, 2);

    % --- per-sample medians over frames (5×1) ------------
    med_P = median(sm_P, 1)';
    med_L = median(sm_L, 1)';
    med_M = median(sm_M, 1)';

    % =====================================================
    % FIGURE
    % =====================================================

    fig = figure('Color',         'w',           ...
                 'Units',         'inches',       ...
                 'Position',      [1.4 1.4 10 5],  ...
                 'PaperUnits',    'inches',        ...
                 'PaperSize',     [6.5 3.2],       ...
                 'PaperPosition', [0 0 6.5 3.2]);

    % =================================================
    % SUBPLOT (a) — frame-wise trajectories
    % =================================================

    ax1 = subplot(1, 2, 1);
    hold(ax1, 'on');

    % individual sample lines
    for s = 1:5
        if useLog
            semilogy(ax1, frames, sm_P(:,s), '-', 'Color', [cPMMA  alphaIndiv], 'LineWidth', 0.8);
            semilogy(ax1, frames, sm_L(:,s), '-', 'Color', [cLPMMA alphaIndiv], 'LineWidth', 0.8);
            semilogy(ax1, frames, sm_M(:,s), '-', 'Color', [cMetal alphaIndiv], 'LineWidth', 0.8);
        else
            plot(ax1, frames, sm_P(:,s), '-', 'Color', [cPMMA  alphaIndiv], 'LineWidth', 0.8);
            plot(ax1, frames, sm_L(:,s), '-', 'Color', [cLPMMA alphaIndiv], 'LineWidth', 0.8);
            plot(ax1, frames, sm_M(:,s), '-', 'Color', [cMetal alphaIndiv], 'LineWidth', 0.8);
        end
    end

    % bold group mean lines
    if useLog
        hP = semilogy(ax1, frames, mu_P, '-', 'Color', cPMMA,  'LineWidth', 2);
        hL = semilogy(ax1, frames, mu_L, '-', 'Color', cLPMMA, 'LineWidth', 2);
        hM = semilogy(ax1, frames, mu_M, '-', 'Color', cMetal,  'LineWidth', 2);
    else
        hP = plot(ax1, frames, mu_P, '-', 'Color', cPMMA,  'LineWidth', 2);
        hL = plot(ax1, frames, mu_L, '-', 'Color', cLPMMA, 'LineWidth', 2);
        hM = plot(ax1, frames, mu_M, '-', 'Color', cMetal,  'LineWidth', 2);
    end

    set(ax1, ...
        'XLim',       [1 20],           ...
        'XTick',      [1 5 10 15 20],   ...
                        'YLim', [1e1 1e4], ...
    'YTick', [1e1 1e2 1e3 1e4], ...
        'TickDir',    'out',            ...
        'TickLength', [0.015 0.015],    ...
        'Box',        'off',            ...
        'FontName',   fontName,         ...
        'FontSize',   fontSize,         ...
        'FontWeight', 'bold',           ...
        'LineWidth',  0.6,              ...
        'XColor',     [0 0 0],          ...
        'YColor',     [0 0 0]);

    if useLog
        set(ax1, 'YScale', 'log');
    end

    grid(ax1, 'on');
    ax1.GridAlpha      = 0.15;
    ax1.GridColor      = [0.5 0.5 0.5];
    ax1.MinorGridAlpha = 0.08;
    if useLog; ax1.YMinorGrid = 'on'; end

    xlabel(ax1, 'Frame number',  ...
        'FontSize', fontSize, 'FontWeight', 'bold', 'FontName', fontName);
    ylabel(ax1, yLab,            ...
        'FontSize', fontSize, 'FontWeight', 'bold', 'FontName', fontName);
    % title(ax1, '(a)',            ...
    %     'FontSize', titleSize, 'FontWeight', 'bold', ...
    %     'FontName', fontName,  'HorizontalAlignment', 'left');
    % 
    % legend(ax1, [hP, hL, hM], {'PMMA','LPMMA','Metal'}, ...
    %     'Location',  'best',        ...
    %     'FontSize',  8,             ...
    %     'FontName',  fontName,      ...
    %     'Box',       'on',          ...
    %     'EdgeColor', [0.7 0.7 0.7], ...
    %     'LineWidth', 0.5);

    text(ax1, -0.18, 1.06, '(a)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom');
% title(ax1, '(a)',                                 ...
%     'FontSize', titleSize, 'FontWeight', 'bold',  ...
%     'FontName', fontName, 'HorizontalAlignment', 'left');

legend(ax1, [hP, hL, hM], ...
    {'PMMA', 'LPMMA', 'Metal'},  ...
    'Location',  'best',         ...
    'FontSize',  16,              ...
    'FontName',  fontName,       ...
    'Box',       'on',           ...
    'EdgeColor', [0.7 0.7 0.7], ...
    'LineWidth', 0.5);



    % =================================================
    % SUBPLOT (b) — box plot + jittered dots
    % =================================================

    ax2 = subplot(1, 2, 2);
    hold(ax2, 'on');

    boxData = [med_P, med_L, med_M];   % 5×3

    bp = boxplot(ax2, boxData,                      ...
        'Labels',      {'PMMA','LPMMA','Metal'},    ...
        'Colors',      [cPMMA; cLPMMA; cMetal],     ...
        'Symbol',      '',                          ...
        'Widths',      0.40,                        ...
        'MedianStyle', 'line',                      ...
        'Notch',       'off');

    set(bp, 'LineWidth', 1.5);

    % color box faces (boxplot reverses order)
    hBox = findobj(ax2, 'Tag', 'Box');
    patch(get(hBox(3),'XData'), get(hBox(3),'YData'), cPMMA,  ...
        'FaceAlpha', 0.20, 'EdgeColor', cPMMA,  'LineWidth', 1.2);
    patch(get(hBox(2),'XData'), get(hBox(2),'YData'), cLPMMA, ...
        'FaceAlpha', 0.20, 'EdgeColor', cLPMMA, 'LineWidth', 1.2);
    patch(get(hBox(1),'XData'), get(hBox(1),'YData'), cMetal, ...
        'FaceAlpha', 0.20, 'EdgeColor', cMetal, 'LineWidth', 1.2);

    % jittered dots
    scatter(ax2, 1+jitter, med_P, 18, cPMMA,  'filled', ...
        'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');
    scatter(ax2, 2+jitter, med_L, 18, cLPMMA, 'filled', ...
        'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');
    scatter(ax2, 3+jitter, med_M, 18, cMetal,  'filled', ...
        'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');

    set(ax2, ...
        'XLim',       [0.4 3.6],     ...
                        'YLim', [1e1 1e4], ...
    'YTick', [1e1 1e2 1e3 1e4], ...
        'TickDir',    'out',         ...
        'TickLength', [0.015 0.015], ...
        'Box',        'off',         ...
        'FontName',   fontName,      ...
        'FontSize',   fontSize,      ...
        'FontWeight', 'bold',        ...
        'LineWidth',  0.6,           ...
        'XColor',     [0 0 0],       ...
        'YColor',     [0 0 0]);

    if useLog
        set(ax2, 'YScale', 'log');
    end

    grid(ax2, 'on');
    ax2.GridAlpha      = 0.15;
    ax2.GridColor      = [0.5 0.5 0.5];
    ax2.MinorGridAlpha = 0.08;
    if useLog; ax2.YMinorGrid = 'on'; end

    % y-label for box plot matches subplot (a)
    ylabel(ax2, ['Median ' yLab],  ...
        'FontSize', fontSize, 'FontWeight', 'bold', 'FontName', fontName);
    % title(ax2, '(b)',              ...
    %     'FontSize', titleSize, 'FontWeight', 'bold', ...
    %     'FontName', fontName,  'HorizontalAlignment', 'left');
text(ax2, -0.18, 1.06, '(b)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom');

legend(ax2, [hP, hL, hM], ...
    {'PMMA', 'LPMMA', 'Metal'}, ...
    'Location','best', ...
    'FontSize',16, ...
    'FontName','Arial', ...
    'Box','on', ...
    'EdgeColor',[0.7 0.7 0.7], ...
    'LineWidth',0.5);

    % =================================================
    % TIGHT LAYOUT
    % =================================================

    % set(ax1, 'Position', [0.09  0.17  0.40  0.72]);
    % set(ax2, 'Position', [0.60  0.17  0.36  0.72]);
set(ax1, 'Position', [0.14 0.16 0.38 0.74]);
set(ax2, 'Position', [0.64 0.16 0.34 0.74]);

    % =================================================
    % SAVE
    % =================================================

    exportgraphics(fig, fullfile(outDir, [fname '.png']), ...
        'Resolution', 600, 'BackgroundColor', 'white');

    exportgraphics(fig, fullfile(outDir, [fname '.pdf']), ...
        'ContentType', 'vector', 'BackgroundColor', 'white');

    savefig(fig, fullfile(outDir, [fname '.fig']));

    fprintf('Saved: %s\n', fname);

end

fprintf('\nAll figures saved to: %s\n', outDir);

%% Only meanIQ plot for same y -range

% =========================================================
% BEAMFORMED IQ MAGNITUDE ONLY
% fSIG_all -> y x x x pulse x frame x repetition x sample
% ==========================================================

PMMA_SIG  = PMMA.fSIG_all;
LPMMA_SIG = LPMMA.fSIG_all;
Metal_SIG = Metal.fSIG_all;

% Mean over y, x, pulse, and repetition
% Output -> frame x sample = 20 x 5
calcMean = @(X) squeeze(mean(mean(mean(mean(X,1),2),3),5));

PMMA_mag_sm  = calcMean(abs(PMMA_SIG));
LPMMA_mag_sm = calcMean(abs(LPMMA_SIG));
Metal_mag_sm = calcMean(abs(Metal_SIG));

% Group mean across 5 samples -> 20 x 1
PMMA_mean  = mean(PMMA_mag_sm,2);
LPMMA_mean = mean(LPMMA_mag_sm,2);
Metal_mean = mean(Metal_mag_sm,2);

% Median over 20 frames for each sample -> 5 x 1
PMMA_med  = median(PMMA_mag_sm,1)';
LPMMA_med = median(LPMMA_mag_sm,1)';
Metal_med = median(Metal_mag_sm,1)';

frames = (1:20)';

% =========================================================
% OUTPUT
% ==========================================================

outDir = 'Y:\Masud\Twinkling_signal_process\Twinkle_paper_Data\L7-4\PW\IQ_paper\IUS';

if ~exist(outDir,'dir')
    mkdir(outDir);
end

% =========================================================
% APPEARANCE
% ==========================================================

cPMMA  = [0.16 0.47 0.84];
cLPMMA = [0.07 0.69 0.48];
cMetal = [0.89 0.29 0.28];

alphaIndiv = 0.20;

fontName  = 'Arial';
fontSize  = 18;
legendSize = 16;

rng(42);
jitter = (rand(5,1)-0.5)*0.12;

% =========================================================
% FIGURE
% ==========================================================

fig = figure('Color','w', ...
    'Units','inches', ...
    'Position',[1.4 1.4 10 5.5], ...
    'PaperUnits','inches', ...
    'PaperSize',[10 5.5], ...
    'PaperPosition',[0 0 10 5.5]);

% =========================================================
% (a) FRAME-WISE MEAN IQ MAGNITUDE
% ==========================================================

ax1 = subplot(1,2,1);
hold(ax1,'on');

% Individual samples
for s = 1:5

    semilogy(ax1,frames,PMMA_mag_sm(:,s),'-', ...
        'Color',[cPMMA alphaIndiv], ...
        'LineWidth',0.8);

    semilogy(ax1,frames,LPMMA_mag_sm(:,s),'-', ...
        'Color',[cLPMMA alphaIndiv], ...
        'LineWidth',0.8);

    semilogy(ax1,frames,Metal_mag_sm(:,s),'-', ...
        'Color',[cMetal alphaIndiv], ...
        'LineWidth',0.8);
end

% Mean across samples
hP = semilogy(ax1,frames,PMMA_mean,'-', ...
    'Color',cPMMA,'LineWidth',2);

hL = semilogy(ax1,frames,LPMMA_mean,'-', ...
    'Color',cLPMMA,'LineWidth',2);

hM = semilogy(ax1,frames,Metal_mean,'-', ...
    'Color',cMetal,'LineWidth',2);

set(ax1, ...
    'YScale','log', ...
    'XLim',[1 20], ...
    'XTick',[1 5 10 15 20], ...
    'TickDir','out', ...
    'TickLength',[0.015 0.015], ...
    'Box','off', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'LineWidth',0.6, ...
    'XColor',[0 0 0], ...
    'YColor',[0 0 0]);

% Force identical log range
ylim(ax1,[1e1 1e5]);
yticks(ax1,[1e1 1e2 1e3 1e4 1e5]);

grid(ax1,'on');
ax1.GridAlpha = 0.15;
ax1.GridColor = [0.5 0.5 0.5];
ax1.YMinorGrid = 'on';
ax1.MinorGridAlpha = 0.08;

xlabel(ax1,'Frame number', ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'FontName',fontName);

ylabel(ax1,'Mean IQ signal magnitude (a.u.)', ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'FontName',fontName);

text(ax1,-0.18,1.06,'(a)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom');

legend(ax1,[hP hL hM], ...
    {'PMMA','LPMMA','Metal'}, ...
    'Location','best', ...
    'FontSize',legendSize, ...
    'FontName',fontName, ...
    'Box','on', ...
    'EdgeColor',[0.7 0.7 0.7]);

% =========================================================
% (b) SAMPLE-WISE MEDIAN IQ MAGNITUDE
% ==========================================================

ax2 = subplot(1,2,2);
hold(ax2,'on');

boxData = [PMMA_med LPMMA_med Metal_med];

bp = boxplot(ax2,boxData, ...
    'Labels',{'PMMA','LPMMA','Metal'}, ...
    'Colors',[cPMMA;cLPMMA;cMetal], ...
    'Symbol','', ...
    'Widths',0.40, ...
    'MedianStyle','line', ...
    'Notch','off');

set(bp,'LineWidth',1.5);

% Colored box faces
hBox = findobj(ax2,'Tag','Box');

patch(get(hBox(3),'XData'),get(hBox(3),'YData'),cPMMA, ...
    'FaceAlpha',0.20, ...
    'EdgeColor',cPMMA, ...
    'LineWidth',1.2);

patch(get(hBox(2),'XData'),get(hBox(2),'YData'),cLPMMA, ...
    'FaceAlpha',0.20, ...
    'EdgeColor',cLPMMA, ...
    'LineWidth',1.2);

patch(get(hBox(1),'XData'),get(hBox(1),'YData'),cMetal, ...
    'FaceAlpha',0.20, ...
    'EdgeColor',cMetal, ...
    'LineWidth',1.2);

% Individual samples
scatter(ax2,1+jitter,PMMA_med,25,cPMMA,'filled', ...
    'MarkerFaceAlpha',0.85, ...
    'MarkerEdgeColor','none');

scatter(ax2,2+jitter,LPMMA_med,25,cLPMMA,'filled', ...
    'MarkerFaceAlpha',0.85, ...
    'MarkerEdgeColor','none');

scatter(ax2,3+jitter,Metal_med,25,cMetal,'filled', ...
    'MarkerFaceAlpha',0.85, ...
    'MarkerEdgeColor','none');

set(ax2, ...
    'YScale','log', ...
    'XLim',[0.4 3.6], ...
    'TickDir','out', ...
    'TickLength',[0.015 0.015], ...
    'Box','off', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'LineWidth',0.6, ...
    'XColor',[0 0 0], ...
    'YColor',[0 0 0]);

ylim(ax2,[1e1 1e5]);
yticks(ax2,[1e1 1e2 1e3 1e4 1e5]);

grid(ax2,'on');
ax2.GridAlpha = 0.15;
ax2.GridColor = [0.5 0.5 0.5];
ax2.YMinorGrid = 'on';
ax2.MinorGridAlpha = 0.08;

ylabel(ax2,'Median IQ signal magnitude (a.u.)', ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'FontName',fontName);

text(ax2,-0.18,1.06,'(b)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom');

% =========================================================
% PANEL POSITIONS
% ==========================================================

set(ax1,'Position',[0.14 0.16 0.38 0.74]);
set(ax2,'Position',[0.64 0.16 0.34 0.74]);

% =========================================================
% SAVE SEPARATELY
% ==========================================================

exportgraphics(fig, ...
    fullfile(outDir,'IQ_Magnitude_combined.png'), ...
    'Resolution',600, ...
    'BackgroundColor','white');

exportgraphics(fig, ...
    fullfile(outDir,'IQ_Magnitude_combined.pdf'), ...
    'ContentType','vector', ...
    'BackgroundColor','white');

savefig(fig, ...
    fullfile(outDir,'IQ_Magnitude_combined.fig'));

fprintf('IQ magnitude figure saved to:\n%s\n',outDir);
%% BF RF without WF

% =========================================================
% DATA:
% bfSIG_rf_all → y × x × pulse × frame × repetition × sample
%                 1    2    3       4         5           6
% =========================================================

PMMA_RF  = abs(PMMA.bfSIG_rf_all);
LPMMA_RF = abs(LPMMA.bfSIG_rf_all);
Metal_RF = abs(Metal.bfSIG_rf_all);

% =========================================================
% MEAN OVER y(1), x(2), pulse(3), rep(5)
% → frame(4) × sample(6)
% → Final: 20 × 5
% =========================================================

calcMean = @(X) squeeze(mean(mean(mean(mean(X, 1), 2), 3), 5));

PMMA_sampleMean  = calcMean(PMMA_RF);
LPMMA_sampleMean = calcMean(LPMMA_RF);
Metal_sampleMean = calcMean(Metal_RF);

% =========================================================
% GROUP MEAN ACROSS SAMPLES → frame × 1  (subplot a)
% =========================================================

PMMA_mean  = mean(PMMA_sampleMean,  2);
LPMMA_mean = mean(LPMMA_sampleMean, 2);
Metal_mean = mean(Metal_sampleMean, 2);

% =========================================================
% MEDIAN OVER FRAMES → 5×1 per sample  (subplot b)
% =========================================================

PMMA_med  = median(PMMA_sampleMean,  1)';
LPMMA_med = median(LPMMA_sampleMean, 1)';
Metal_med = median(Metal_sampleMean, 1)';

frames = (1:20)';

% =========================================================
% OUTPUT FOLDER
% =========================================================

outDir = 'Y:\Masud\Twinkling_signal_process\Twinkle_paper_Data\L7-4\PW\BF_RF_paper\IUS';
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

% =========================================================
% SHARED SETTINGS
% =========================================================

cPMMA      = [0.16, 0.47, 0.84];
cLPMMA     = [0.07, 0.69, 0.48];
cMetal     = [0.89, 0.29, 0.28];
alphaIndiv = 0.20;

fontName  = 'Arial';
fontSize  = 11;
titleSize = 14;

rng(42);
jitter = (rand(5,1) - 0.5) * 0.12;

% =========================================================
% FIGURE — 6.5 × 3.2 inches (fits Word page, 1" margins)
% =========================================================

fig = figure('Color','w', ...
    'Units','inches', ...
    'Position',[1.4 1.4 10 5.5], ...
    'PaperUnits','inches', ...
    'PaperSize',[10 5.5], ...
    'PaperPosition',[0 0 10 5.5]);

fontName  = 'Arial';
fontSize  = 18;
titleSize = 18;
legendSize = 18;


% =========================================================
% SUBPLOT (a) — Frame-wise trajectories
% =========================================================

ax1 = subplot(1, 2, 1);
hold(ax1, 'on');

% --- individual sample lines (thin, translucent) ----------
for s = 1:5
    semilogy(ax1, frames, PMMA_sampleMean(:,s),  '-', ...
        'Color', [cPMMA  alphaIndiv], 'LineWidth', 0.8);
    semilogy(ax1, frames, LPMMA_sampleMean(:,s), '-', ...
        'Color', [cLPMMA alphaIndiv], 'LineWidth', 0.8);
    semilogy(ax1, frames, Metal_sampleMean(:,s), '-', ...
        'Color', [cMetal alphaIndiv], 'LineWidth', 0.8);
end

% --- bold group mean lines --------------------------------
hP = semilogy(ax1, frames, PMMA_mean,  '-', 'Color', cPMMA,  'LineWidth', 2);
hL = semilogy(ax1, frames, LPMMA_mean, '-', 'Color', cLPMMA, 'LineWidth', 2);
hM = semilogy(ax1, frames, Metal_mean, '-', 'Color', cMetal,  'LineWidth', 2);

set(ax1, ...
    'YScale',     'log', ...
    'XLim',       [1 20], ...
    'XTick',      [1 5 10 15 20], ...
            'YLim', [1e1 1e5], ...
    'YTick', [1e1 1e2 1e3 1e4 1e5], ...
    'TickDir',    'out', ...
    'TickLength', [0.015 0.015], ...
    'Box',        'off', ...
    'FontName',   fontName, ...
    'FontSize',   fontSize, ...
    'FontWeight', 'bold', ...
    'LineWidth',  0.6, ...
    'XColor',     [0 0 0], ...
    'YColor',     [0 0 0]);

grid(ax1, 'on');
ax1.GridAlpha      = 0.15;
ax1.GridColor      = [0.5 0.5 0.5];
ax1.MinorGridAlpha = 0.08;
ax1.YMinorGrid     = 'on';

xlabel(ax1, 'Frame number',                       ...
    'FontSize', fontSize, 'FontWeight', 'bold', 'FontName', fontName);
ylabel(ax1, 'Mean BF RF signal magnitude (a.u.)', ...
    'FontSize', fontSize, 'FontWeight', 'bold', 'FontName', fontName);
% title(ax1, '(a)',                                  ...
%     'FontSize', titleSize, 'FontWeight', 'bold',   ...
%     'FontName', fontName, 'HorizontalAlignment', 'left');
% 
% legend(ax1, [hP, hL, hM], {'PMMA', 'LPMMA', 'Metal'}, ...
%     'Location',  'best',        ...
%     'FontSize',  8,             ...
%     'FontName',  fontName,      ...
%     'Box',       'on',          ...
%     'EdgeColor', [0.7 0.7 0.7], ...
%     'LineWidth', 0.5);

text(ax1, -0.18, 1.06, '(a)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom');
% title(ax1, '(a)',                                 ...
%     'FontSize', titleSize, 'FontWeight', 'bold',  ...
%     'FontName', fontName, 'HorizontalAlignment', 'left');

legend(ax1, [hP, hL, hM], ...
    {'PMMA', 'LPMMA', 'Metal'},  ...
    'Location',  'best',         ...
    'FontSize',  16,              ...
    'FontName',  fontName,       ...
    'Box',       'on',           ...
    'EdgeColor', [0.7 0.7 0.7], ...
    'LineWidth', 0.5);



% =========================================================
% SUBPLOT (b) — Box plot of per-sample median RF magnitude
% =========================================================

ax2 = subplot(1, 2, 2);
hold(ax2, 'on');

boxData = [PMMA_med, LPMMA_med, Metal_med];   % 5 × 3

bp = boxplot(ax2, boxData,                     ...
    'Labels',      {'PMMA', 'LPMMA', 'Metal'}, ...
    'Colors',      [cPMMA; cLPMMA; cMetal],    ...
    'Symbol',      '',                         ...
    'Widths',      0.40,                       ...
    'MedianStyle', 'line',                     ...
    'Notch',       'off');

set(bp, 'LineWidth', 1.5);

% --- color box faces (boxplot reverses order) -------------
hBox = findobj(ax2, 'Tag', 'Box');
patch(get(hBox(3), 'XData'), get(hBox(3), 'YData'), cPMMA,  ...
    'FaceAlpha', 0.20, 'EdgeColor', cPMMA,  'LineWidth', 1.2);
patch(get(hBox(2), 'XData'), get(hBox(2), 'YData'), cLPMMA, ...
    'FaceAlpha', 0.20, 'EdgeColor', cLPMMA, 'LineWidth', 1.2);
patch(get(hBox(1), 'XData'), get(hBox(1), 'YData'), cMetal,  ...
    'FaceAlpha', 0.20, 'EdgeColor', cMetal,  'LineWidth', 1.2);

% --- jittered individual sample dots ----------------------
scatter(ax2, 1 + jitter, PMMA_med,  18, cPMMA,  'filled', ...
    'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');
scatter(ax2, 2 + jitter, LPMMA_med, 18, cLPMMA, 'filled', ...
    'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');
scatter(ax2, 3 + jitter, Metal_med, 18, cMetal,  'filled', ...
    'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');

set(ax2, ...
    'YScale',     'log', ...
    'XLim',       [0.4 3.6], ...
            'YLim', [1e1 1e5], ...
    'YTick', [1e1 1e2 1e3 1e4 1e5], ...
    'TickDir',    'out', ...
    'TickLength', [0.015 0.015], ...
    'Box',        'off', ...
    'FontName',   fontName, ...
    'FontSize',   fontSize, ...
    'FontWeight', 'bold', ...
    'LineWidth',  0.6, ...
    'XColor',     [0 0 0], ...
    'YColor',     [0 0 0]);



grid(ax2, 'on');
ax2.GridAlpha      = 0.15;
ax2.GridColor      = [0.5 0.5 0.5];
ax2.YMinorGrid     = 'on';
ax2.MinorGridAlpha = 0.08;

ylabel(ax2, 'Median BF RF signal magnitude (a.u.)', ...
    'FontSize', fontSize, 'FontWeight', 'bold', 'FontName', fontName);
text(ax2, -0.18, 1.06, '(b)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom');
legend(ax1, [hP, hL, hM], ...
    {'PMMA', 'LPMMA', 'Metal'},  ...
    'Location',  'best',         ...
    'FontSize',  16,              ...
    'FontName',  fontName,       ...
    'Box',       'on',           ...
    'EdgeColor', [0.7 0.7 0.7], ...
    'LineWidth', 0.5);


% =========================================================
% TIGHT LAYOUT
% =========================================================

set(ax1, 'Position', [0.12 0.16 0.38 0.74]);
set(ax2, 'Position', [0.62 0.16 0.34 0.74]);


% =========================================================
% SAVE — PNG, PDF, .fig
% =========================================================

exportgraphics(fig, fullfile(outDir, 'BF_RF_combined_figure(No_WF).png'), ...
    'Resolution', 600, 'BackgroundColor', 'white');

exportgraphics(fig, fullfile(outDir, 'BF_RF_combined_figure (No_WF).pdf'), ...
    'ContentType', 'vector', 'BackgroundColor', 'white');

savefig(fig, fullfile(outDir, 'BF_RF_combined_figure (No_WF).fig'));

fprintf('Saved to: %s\n', outDir);

%% Pulse wise demonstration

% =========================================================
% DATA
%
% bfSIG_rf_all:
%
% y × x × pulse × frame × repetition × sample
%
% 1    2    3       4         5          6
%
% Size:
% 25 × 31 × 14 × 20 × 5 × 5
%
% =========================================================

% PMMA_RF  = abs(PMMA.fSIG_all);
% LPMMA_RF = abs(LPMMA.fSIG_all);
% Metal_RF = abs(Metal.fSIG_all);

PMMA_RF  = abs(PMMA.fSIG_rf_all);
LPMMA_RF = abs(LPMMA.fSIG_rf_all);
Metal_RF = abs(Metal.fSIG_rf_all);

% =========================================================
% CHECK ORIGINAL DATA SIZE
% =========================================================

fprintf('\nOriginal data dimensions:\n');

fprintf('PMMA  : %s\n', mat2str(size(PMMA_RF)));
fprintf('LPMMA : %s\n', mat2str(size(LPMMA_RF)));
fprintf('Metal : %s\n', mat2str(size(Metal_RF)));


% =========================================================
% PULSE-WISE AVERAGING
%
% Average over:
%
% y          → dimension 1
% x          → dimension 2
% frame      → dimension 4
% repetition → dimension 5
%
% KEEP:
%
% pulse      → dimension 3
% sample     → dimension 6
%
% Final result:
%
% 14 pulses × 5 samples
%
% =========================================================

PMMA_sampleMean = squeeze( ...
    mean(mean(mean(mean(PMMA_RF,1),2),4),5));

LPMMA_sampleMean = squeeze( ...
    mean(mean(mean(mean(LPMMA_RF,1),2),4),5));

Metal_sampleMean = squeeze( ...
    mean(mean(mean(mean(Metal_RF,1),2),4),5));


% =========================================================
% CHECK RESULTING DIMENSIONS
% =========================================================

fprintf('\nPulse-wise data dimensions:\n');

fprintf('PMMA  : %s\n', mat2str(size(PMMA_sampleMean)));
fprintf('LPMMA : %s\n', mat2str(size(LPMMA_sampleMean)));
fprintf('Metal : %s\n', mat2str(size(Metal_sampleMean)));


% =========================================================
% GROUP MEAN ACROSS SAMPLES
%
% pulse × 1
%
% =========================================================

PMMA_mean  = mean(PMMA_sampleMean,2,'omitnan');
LPMMA_mean = mean(LPMMA_sampleMean,2,'omitnan');
Metal_mean = mean(Metal_sampleMean,2,'omitnan');


% =========================================================
% MEDIAN OVER PULSES
%
% One value per sample
%
% 5 × 1
%
% =========================================================

PMMA_med  = median(PMMA_sampleMean,1,'omitnan')';
LPMMA_med = median(LPMMA_sampleMean,1,'omitnan')';
Metal_med = median(Metal_sampleMean,1,'omitnan')';


% =========================================================
% PULSE NUMBER
% =========================================================

pulses = (1:size(PMMA_sampleMean,1))';


% =========================================================
% OUTPUT FOLDER
% =========================================================

outDir = ...
'Y:\Masud\Twinkling_signal_process\Twinkle_paper_Data\L7-4\PW\BF_RF_paper\IUS';

if ~exist(outDir,'dir')
    mkdir(outDir);
end


% =========================================================
% COLORS
% =========================================================

cPMMA  = [0.16, 0.47, 0.84];
cLPMMA = [0.07, 0.69, 0.48];
cMetal = [0.89, 0.29, 0.28];

alphaIndiv = 0.20;


% =========================================================
% FIGURE
% =========================================================

ffig = figure('Color','w', ...
    'Units','inches', ...
    'Position',[1.4 1.4 10 5.5], ...
    'PaperUnits','inches', ...
    'PaperSize',[10 5.5], ...
    'PaperPosition',[0 0 10 5.5]);

fontName  = 'Arial';
fontSize  = 18;
titleSize = 18;
legendSize = 18;



% =========================================================
% SUBPLOT (a)
% PULSE-WISE TRAJECTORIES
% =========================================================

ax1 = subplot(1,2,1);

hold(ax1,'on');


% ---------------------------------------------------------
% Individual sample trajectories
% ---------------------------------------------------------

for s = 1:size(PMMA_sampleMean,2)

    semilogy(ax1, ...
        pulses, ...
        PMMA_sampleMean(:,s), ...
        '-', ...
        'Color',[cPMMA alphaIndiv], ...
        'LineWidth',0.8);

    semilogy(ax1, ...
        pulses, ...
        LPMMA_sampleMean(:,s), ...
        '-', ...
        'Color',[cLPMMA alphaIndiv], ...
        'LineWidth',0.8);

    semilogy(ax1, ...
        pulses, ...
        Metal_sampleMean(:,s), ...
        '-', ...
        'Color',[cMetal alphaIndiv], ...
        'LineWidth',0.8);

end


% ---------------------------------------------------------
% Group mean
% ---------------------------------------------------------

hP = semilogy(ax1, ...
    pulses,PMMA_mean, ...
    '-', ...
    'Color',cPMMA, ...
    'LineWidth',2);

hL = semilogy(ax1, ...
    pulses,LPMMA_mean, ...
    '-', ...
    'Color',cLPMMA, ...
    'LineWidth',2);

hM = semilogy(ax1, ...
    pulses,Metal_mean, ...
    '-', ...
    'Color',cMetal, ...
    'LineWidth',2);


% ---------------------------------------------------------
% Axis formatting
% ---------------------------------------------------------

set(ax1, ...
    'YScale','log', ...
    'XLim',[1 14], ...
    'XTick',[1 2 4 6 8 10 12 14], ...
        'YLim', [1e1 1e4], ...
    'YTick', [1e1 1e2 1e3 1e4], ...
    'TickDir','out', ...
    'TickLength',[0.015 0.015], ...
    'Box','off', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'LineWidth',0.6, ...
    'XColor',[0 0 0], ...
    'YColor',[0 0 0]);


grid(ax1,'on');

ax1.GridAlpha      = 0.15;
ax1.GridColor      = [0.5 0.5 0.5];
ax1.MinorGridAlpha = 0.08;
ax1.YMinorGrid     = 'on';


% ---------------------------------------------------------
% Labels
% ---------------------------------------------------------

xlabel(ax1, ...
    'Pulse number', ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'FontName',fontName);

ylabel(ax1, ...
    'Mean BF RF signal magnitude (a.u.)', ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'FontName',fontName);


% ---------------------------------------------------------
% Panel label
% ---------------------------------------------------------

title(ax1, ...
    '(a)', ...
    'FontSize',titleSize, ...
    'FontWeight','bold', ...
    'FontName',fontName, ...
    'HorizontalAlignment','left');


% ---------------------------------------------------------
% Legend
% ---------------------------------------------------------

text(ax1, -0.18, 1.06, '(a)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom');
% title(ax1, '(a)',                                 ...
%     'FontSize', titleSize, 'FontWeight', 'bold',  ...
%     'FontName', fontName, 'HorizontalAlignment', 'left');

legend(ax1, [hP, hL, hM], ...
    {'PMMA', 'LPMMA', 'Metal'},  ...
    'Location',  'best',         ...
    'FontSize',  16,              ...
    'FontName',  fontName,       ...
    'Box',       'on',           ...
    'EdgeColor', [0.7 0.7 0.7], ...
    'LineWidth', 0.5);


% =========================================================
% SUBPLOT (b)
% PER-SAMPLE MEDIAN BF RF
% =========================================================

ax2 = subplot(1,2,2);

hold(ax2,'on');


% ---------------------------------------------------------
% Combine data
% ---------------------------------------------------------

boxData = [ ...
    PMMA_med, ...
    LPMMA_med, ...
    Metal_med];


% ---------------------------------------------------------
% Boxplot
% ---------------------------------------------------------

bp = boxplot(ax2, ...
    boxData, ...
    'Labels',{'PMMA','LPMMA','Metal'}, ...
    'Colors',[cPMMA;cLPMMA;cMetal], ...
    'Symbol','', ...
    'Widths',0.40, ...
    'MedianStyle','line', ...
    'Notch','off');

set(bp,'LineWidth',1.5);


% ---------------------------------------------------------
% Color box faces
% ---------------------------------------------------------

hBox = findobj(ax2,'Tag','Box');


patch( ...
    get(hBox(3),'XData'), ...
    get(hBox(3),'YData'), ...
    cPMMA, ...
    'FaceAlpha',0.20, ...
    'EdgeColor',cPMMA, ...
    'LineWidth',1.2);

patch( ...
    get(hBox(2),'XData'), ...
    get(hBox(2),'YData'), ...
    cLPMMA, ...
    'FaceAlpha',0.20, ...
    'EdgeColor',cLPMMA, ...
    'LineWidth',1.2);

patch( ...
    get(hBox(1),'XData'), ...
    get(hBox(1),'YData'), ...
    cMetal, ...
    'FaceAlpha',0.20, ...
    'EdgeColor',cMetal, ...
    'LineWidth',1.2);


% ---------------------------------------------------------
% Individual sample points
% ---------------------------------------------------------

rng(42);

nSamples = length(PMMA_med);

jitter = ...
    (rand(nSamples,1)-0.5)*0.12;


scatter(ax2, ...
    1+jitter, ...
    PMMA_med, ...
    18, ...
    cPMMA, ...
    'filled', ...
    'MarkerFaceAlpha',0.85, ...
    'MarkerEdgeColor','none');

scatter(ax2, ...
    2+jitter, ...
    LPMMA_med, ...
    18, ...
    cLPMMA, ...
    'filled', ...
    'MarkerFaceAlpha',0.85, ...
    'MarkerEdgeColor','none');

scatter(ax2, ...
    3+jitter, ...
    Metal_med, ...
    18, ...
    cMetal, ...
    'filled', ...
    'MarkerFaceAlpha',0.85, ...
    'MarkerEdgeColor','none');


% ---------------------------------------------------------
% Axis formatting
% ---------------------------------------------------------

set(ax2, ...
    'YScale','log', ...
    'XLim',[0.4 3.6], ...
        'YLim', [1e1 1e4], ...
    'YTick', [1e1 1e2 1e3 1e4], ...
    'TickDir','out', ...
    'TickLength',[0.015 0.015], ...
    'Box','off', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'LineWidth',0.6, ...
    'XColor',[0 0 0], ...
    'YColor',[0 0 0]);


grid(ax2,'on');

ax2.GridAlpha      = 0.15;
ax2.GridColor      = [0.5 0.5 0.5];
ax2.YMinorGrid     = 'on';
ax2.MinorGridAlpha = 0.08;


ylabel(ax2, ...
    'Median BF RF signal magnitude (a.u.)', ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'FontName',fontName);


text(ax2, -0.18, 1.06, '(b)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom');
legend(ax1, [hP, hL, hM], ...
    {'PMMA', 'LPMMA', 'Metal'},  ...
    'Location',  'best',         ...
    'FontSize', 16,              ...
    'FontName',  fontName,       ...
    'Box',       'on',           ...
    'EdgeColor', [0.7 0.7 0.7], ...
    'LineWidth', 0.5);


% =========================================================
% TIGHT LAYOUT
% =========================================================

set(ax1, 'Position', [0.12 0.16 0.38 0.74]);
set(ax2, 'Position', [0.62 0.16 0.34 0.74]);


% =========================================================
% SAVE
% =========================================================

% exportgraphics(fig, ...
%     fullfile(outDir,'BF_RF_pulse_combined_figure.png'), ...
%     'Resolution',600, ...
%     'BackgroundColor','white');
% 
% exportgraphics(fig, ...
%     fullfile(outDir,'BF_RF_pulse_combined_figure.pdf'), ...
%     'ContentType','vector', ...
%     'BackgroundColor','white');
% 
% savefig(fig, ...
%     fullfile(outDir,'BF_RF_pulse_combined_figure.fig'));
% 
% 
% fprintf('\n============================================\n');
% fprintf('Pulse-wise BF RF figure saved to:\n%s\n',outDir);
% fprintf('============================================\n');

% =========================================================
% SAVE — PNG, PDF, FIG
% =========================================================

fig = gcf;

if ~isvalid(fig)
    error('Current figure is not valid.');
end

set(fig,'PaperPositionMode','auto');

pngFile = fullfile(outDir,'BF_RF_pulse_combined_figure.png');
pdfFile = fullfile(outDir,'BF_RF_pulse_combined_figure.pdf');
figFile = fullfile(outDir,'BF_RF_pulse_combined_figure.fig');

print(fig, pngFile, '-dpng', '-r600');

set(fig,'Renderer','painters');
print(fig, pdfFile, '-dpdf', '-painters', '-bestfit');

savefig(fig, figFile);

fprintf('\n============================================\n');
fprintf('Pulse-wise BF RF figure saved to:\n%s\n', outDir);
fprintf('============================================\n');

%% =========================================================
% RF + IQ TEMPORAL VARIABILITY
%
% Pulse-wise:
%   Use middle 12 pulses only = pulses 2:13
%
% Frame-wise:
%   PMMA/LPMMA = all 20 frames
%   Metal      = exclude frames 5:7
%
% Final reported values:
%   Mean temporal SD +/- between-sample SD across 5 samples
% ==========================================================

%% =========================================================
% LOAD DATA
% ==========================================================

PMMA_RF  = abs(PMMA.fSIG_rf_all);
LPMMA_RF = abs(LPMMA.fSIG_rf_all);
Metal_RF = abs(Metal.fSIG_rf_all);

PMMA_IQ  = abs(PMMA.fSIG_all);
LPMMA_IQ = abs(LPMMA.fSIG_all);
Metal_IQ = abs(Metal.fSIG_all);

pulseIdx    = 2:13;                 % middle 12 pulses
allFrames   = 1:20;
metalFrames = setdiff(1:20,5:7);    % remove metal frames 5-7


% =========================================================
% RF — FRAME-WISE
%
% Average over y, x, pulse, repetition
% Keep: frame x sample = 20 x 5
% ==========================================================

PMMA_RF_frame = squeeze( ...
    mean(mean(mean(mean(PMMA_RF,1,'omitnan'), ...
                         2,'omitnan'), ...
                         3,'omitnan'), ...
                         5,'omitnan'));

LPMMA_RF_frame = squeeze( ...
    mean(mean(mean(mean(LPMMA_RF,1,'omitnan'), ...
                         2,'omitnan'), ...
                         3,'omitnan'), ...
                         5,'omitnan'));

Metal_RF_frame = squeeze( ...
    mean(mean(mean(mean(Metal_RF,1,'omitnan'), ...
                         2,'omitnan'), ...
                         3,'omitnan'), ...
                         5,'omitnan'));

% SD across frames for each sample
PMMA_RF_frameSD  = std(PMMA_RF_frame(allFrames,:),0,1,'omitnan');
LPMMA_RF_frameSD = std(LPMMA_RF_frame(allFrames,:),0,1,'omitnan');
Metal_RF_frameSD = std(Metal_RF_frame(metalFrames,:),0,1,'omitnan');


% =========================================================
% RF — PULSE-WISE
%
% Average over y, x, frame, repetition
% Keep: pulse x sample = 14 x 5
% Then use pulses 2:13
% ==========================================================

PMMA_RF_pulse = squeeze( ...
    mean(mean(mean(mean(PMMA_RF,1,'omitnan'), ...
                         2,'omitnan'), ...
                         4,'omitnan'), ...
                         5,'omitnan'));

LPMMA_RF_pulse = squeeze( ...
    mean(mean(mean(mean(LPMMA_RF,1,'omitnan'), ...
                         2,'omitnan'), ...
                         4,'omitnan'), ...
                         5,'omitnan'));

Metal_RF_pulse = squeeze( ...
    mean(mean(mean(mean(Metal_RF,1,'omitnan'), ...
                         2,'omitnan'), ...
                         4,'omitnan'), ...
                         5,'omitnan'));

% SD across middle 12 pulses for each sample
PMMA_RF_pulseSD  = std(PMMA_RF_pulse(pulseIdx,:),0,1,'omitnan');
LPMMA_RF_pulseSD = std(LPMMA_RF_pulse(pulseIdx,:),0,1,'omitnan');
Metal_RF_pulseSD = std(Metal_RF_pulse(pulseIdx,:),0,1,'omitnan');


% =========================================================
% IQ — FRAME-WISE
% ==========================================================

PMMA_IQ_frame = squeeze( ...
    mean(mean(mean(mean(PMMA_IQ,1,'omitnan'), ...
                         2,'omitnan'), ...
                         3,'omitnan'), ...
                         5,'omitnan'));

LPMMA_IQ_frame = squeeze( ...
    mean(mean(mean(mean(LPMMA_IQ,1,'omitnan'), ...
                         2,'omitnan'), ...
                         3,'omitnan'), ...
                         5,'omitnan'));

Metal_IQ_frame = squeeze( ...
    mean(mean(mean(mean(Metal_IQ,1,'omitnan'), ...
                         2,'omitnan'), ...
                         3,'omitnan'), ...
                         5,'omitnan'));

% SD across frames for each sample
PMMA_IQ_frameSD  = std(PMMA_IQ_frame(allFrames,:),0,1,'omitnan');
LPMMA_IQ_frameSD = std(LPMMA_IQ_frame(allFrames,:),0,1,'omitnan');
Metal_IQ_frameSD = std(Metal_IQ_frame(metalFrames,:),0,1,'omitnan');


% =========================================================
% IQ — PULSE-WISE
% ==========================================================

PMMA_IQ_pulse = squeeze( ...
    mean(mean(mean(mean(PMMA_IQ,1,'omitnan'), ...
                         2,'omitnan'), ...
                         4,'omitnan'), ...
                         5,'omitnan'));

LPMMA_IQ_pulse = squeeze( ...
    mean(mean(mean(mean(LPMMA_IQ,1,'omitnan'), ...
                         2,'omitnan'), ...
                         4,'omitnan'), ...
                         5,'omitnan'));

Metal_IQ_pulse = squeeze( ...
    mean(mean(mean(mean(Metal_IQ,1,'omitnan'), ...
                         2,'omitnan'), ...
                         4,'omitnan'), ...
                         5,'omitnan'));

% SD across middle 12 pulses for each sample
PMMA_IQ_pulseSD  = std(PMMA_IQ_pulse(pulseIdx,:),0,1,'omitnan');
LPMMA_IQ_pulseSD = std(LPMMA_IQ_pulse(pulseIdx,:),0,1,'omitnan');
Metal_IQ_pulseSD = std(Metal_IQ_pulse(pulseIdx,:),0,1,'omitnan');


% =========================================================
% SUMMARY ACROSS 5 SAMPLES
% ==========================================================

Material = {'PMMA'; 'LPMMA'; 'Metal'};

RF_Frame_SD_Mean = [ ...
    mean(PMMA_RF_frameSD,'omitnan');
    mean(LPMMA_RF_frameSD,'omitnan');
    mean(Metal_RF_frameSD,'omitnan')];

RF_Frame_SD_Between = [ ...
    std(PMMA_RF_frameSD,0,'omitnan');
    std(LPMMA_RF_frameSD,0,'omitnan');
    std(Metal_RF_frameSD,0,'omitnan')];

RF_Pulse_SD_Mean = [ ...
    mean(PMMA_RF_pulseSD,'omitnan');
    mean(LPMMA_RF_pulseSD,'omitnan');
    mean(Metal_RF_pulseSD,'omitnan')];

RF_Pulse_SD_Between = [ ...
    std(PMMA_RF_pulseSD,0,'omitnan');
    std(LPMMA_RF_pulseSD,0,'omitnan');
    std(Metal_RF_pulseSD,0,'omitnan')];

IQ_Frame_SD_Mean = [ ...
    mean(PMMA_IQ_frameSD,'omitnan');
    mean(LPMMA_IQ_frameSD,'omitnan');
    mean(Metal_IQ_frameSD,'omitnan')];

IQ_Frame_SD_Between = [ ...
    std(PMMA_IQ_frameSD,0,'omitnan');
    std(LPMMA_IQ_frameSD,0,'omitnan');
    std(Metal_IQ_frameSD,0,'omitnan')];

IQ_Pulse_SD_Mean = [ ...
    mean(PMMA_IQ_pulseSD,'omitnan');
    mean(LPMMA_IQ_pulseSD,'omitnan');
    mean(Metal_IQ_pulseSD,'omitnan')];

IQ_Pulse_SD_Between = [ ...
    std(PMMA_IQ_pulseSD,0,'omitnan');
    std(LPMMA_IQ_pulseSD,0,'omitnan');
    std(Metal_IQ_pulseSD,0,'omitnan')];


% =========================================================
% FINAL TABLE
% ==========================================================

T_summary = table( ...
    Material, ...
    RF_Frame_SD_Mean, RF_Frame_SD_Between, ...
    RF_Pulse_SD_Mean, RF_Pulse_SD_Between, ...
    IQ_Frame_SD_Mean, IQ_Frame_SD_Between, ...
    IQ_Pulse_SD_Mean, IQ_Pulse_SD_Between);

disp(T_summary);


% =========================================================
% PRINT MEAN +/- SD
% ==========================================================

fprintf('\n============================================================\n');
fprintf(' RF and IQ Temporal Variability\n');
fprintf(' Pulse-wise: pulses 2-13\n');
fprintf(' Frame-wise: Metal frames 5-7 excluded\n');
fprintf('============================================================\n\n');

for i = 1:3

    fprintf('%s\n',Material{i});

    fprintf('  RF Frame-wise : %.3f +/- %.3f a.u.\n', ...
        RF_Frame_SD_Mean(i),RF_Frame_SD_Between(i));

    fprintf('  RF Pulse-wise : %.3f +/- %.3f a.u.\n', ...
        RF_Pulse_SD_Mean(i),RF_Pulse_SD_Between(i));

    fprintf('  IQ Frame-wise : %.3f +/- %.3f a.u.\n', ...
        IQ_Frame_SD_Mean(i),IQ_Frame_SD_Between(i));

    fprintf('  IQ Pulse-wise : %.3f +/- %.3f a.u.\n\n', ...
        IQ_Pulse_SD_Mean(i),IQ_Pulse_SD_Between(i));

end


% =========================================================
% SAVE RESULTS
% ==========================================================

outputFile = fullfile(outDir, ...
    'RF_IQ_Frame_Pulse_Variability.xlsx');

writetable(T_summary,outputFile,'Sheet','Summary');

fprintf('\nSaved to:\n%s\n',outputFile);